### ISSUE TITLE
Performance of locking

### ISSUE THREAD

**Issue by quinnj** [oxinabox/InternedStrings.jl#4]
I've been doing some soul-searching w/ WeakRefStrings lately and some benchmarking between WeakRefString, InternedString, SubString, and regular Strings. One thing I noticed is the call to `lock` actually causes a 2x performance hit, which hurts in hot inner loops.

It made me wonder if there could be a way to "turn off" the locking for single-threaded applications (which honestly, are most in julia right now).

Any ideas on this?

**Comment by oxinabox** [comment]
Yeah, see also the discourse with @ScottPJones on [discourse](https://discourse.julialang.org/t/ann-internedstrings-jl-allocate-strings-once-and-reuse-them/7344/7)
That involves something like double checked locking where you only acquire the lock if it is needed.

Changes to the locking in general below in https://github.com/JuliaLang/julia/blob/2138144d3a0821f0e8de762c709ba90f4127a9a9/base/weakkeydict.jl#L73-L75
Since this is actually common functionality for `Base.WeakKeyDict`
also used in serialisation.

I wonder if:

```

islocked(wkh::WeakKeyDict) = @static ENV["JULIA_NUM_THREADS"] > 1 ? islocked(wkh.lock) : false
lock(f, wkh::WeakKeyDict) = @static ENV["JULIA_NUM_THREADS"] > 1 ? lock(f, wkh.lock) : true
trylock(f, wkh::WeakKeyDict) = @static ENV["JULIA_NUM_THREADS"] > 1 ? trylock(f, wkh.lock) : true
```

would work for what you are suggestion to turn off the locking

**Comment by xiaodaigh** [comment]
bump

**Comment by oxinabox** [comment]
I tested just commenting out the lock

It only reduced: `@btime include("test/runtests.jl")`
from 33.27 seconds 
down to 30.30 seconds.

With just  checking the constructor time, difference about <20%  slower with having the lock vs without

So I do not think the lock is a critical point to optimize.

**Comment by ScottPJones** [comment]
It depends - the issue with locking is not so much the cost on a single process, but rather, how much it slows everything down if you have 4, 8, 16, ... thousands of processes all accessing that resource.
(At ISC, we had shared resources used by up to 64K concurrent processes [and we were talking about needed to get rid of that old limit when I left 3 years ago])

**Comment by oxinabox** [comment]
yes,
but @quinnj 's observation was about single threaded.
And (though I can't find it now) the thing that @xiaodaigh  is working on was single threaded too I think.

**Comment by ScottPJones** [comment]
Ah - OK - I was thinking about the whole locking performance discussion (and of course, why lock, if it's only going to be single threaded)

**Comment by oxinabox** [comment]
Closing:
I see no where to go with this, (I don't care to implement my own Dict type to improve multithreaded performance right now)
 and I am getting good performance improvements in #5
